version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    image: trajkovvlatko/daily-buddy
    ports:
      - "8910:8910"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DAILY_BUDDY_DATABASE_URL}
