version: '3.9'
services:
  database:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_DATABASE: 'daily_buddy_development'
      MYSQL_USER: 'vlatko'
      MYSQL_PASSWORD: 'vlatkodev'
      MYSQL_ROOT_PASSWORD: 'vlatkodev'
    ports:
      - '13306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_database:/var/lib/mysql
volumes:
  mysql_database:
