version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: daily-buddy
    ports:
      - "8910:8910"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
