services:
  database:
    image: postgres:13
    volumes:
      - database-data:/var/opt/daily-buddy-database/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=daily_buddy_development
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "12345:5432"
volumes:
  database-data:
